# Nixpacks configuration for Railway deployment
[phases.setup]
aptPkgs = ["ffmpeg"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --workers 4 app:app"